version: '2.4'

services:
  gateway:
    image: traefik:1.7.12
    ports:
      - "80:80" # HTTP exposed
      - "443:443" # HTTP exposed
      - "8081:8081" # HTTP Administration exposed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/acme.json:/acme.json
    command:
      - --logLevel=ERROR
      - --docker
      - --docker.watch
      - --docker.constraints=tag==v5
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.domain=mydomain.com
      - --defaultentrypoints=http,https
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 Compress:true TLS"
      - --retry
      - --web
      - --web.address=8081
      - --acme.email=budaevqwerty@gmail.com
      - --acme.storage=acme.json
      - --acme.onHostRule=true
      - --acme.entrypoint=https
      - --acme.httpchallenge.entrypoint=http
      - --acme.domains=mydomain.com,www.mydomain.com

    restart: always