spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/orm-demo
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: debug