version: '2.4'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: orm-demo
    volumes:
      - test-db:/var/lib/postgresql/data
    restart: on-failure
    ports:
       - "5432:5432"

volumes:
  test-db:
